<h1 style='color:red'><b>NumPy for Machine Learning 

### NumPy is a library of Python that will help in analyzing the data. It is used by individuals who deal with Data science. 

<h2 style="color:blue"><b> Installation

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


<h2 style="color:rgb(246,99,09)"><b>Topic 1: What are Numpy Arrrays?

### While working with NumPy for data science, mostly we have to deal with NumPy arrays. These arrays are of two types:

### 1. Matrices

###           Matrices are usually two-dimensional but they can still have either only one row or one column.

### 2. Vectors

###           Vectors on the other hand are strictly one-dimensional.

<h2 style="color:blue"><b>Importing NumPy

In [5]:
import numpy as np

<h2 style="color:blue"><b>How to create 1-D NumPy Arrays?

In [10]:
list=[1,2,3,4,5]
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

<h2 style="color:blue"><b>How to create 2-D NumPy Arrays?

In [11]:
list2=[[1,2,3],[4,5,6]]
arr2 = np.array([[1,2,3,10],[4,5,6,12]])
arr2

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 12]])

<h2 style="color:blue"><b>How to create multi-dimensional NumPy Arrays?

In [27]:
arr4 = np.array(
    [
        [
            [
                [1,2,3,4,5]
            ]
        ]
    ]
    )
arr4

array([[[[1, 2, 3, 4, 5]]]])

<h2 style="color:rgb(246,99,09)"><b>Topic 2: How to create NumPy Arrays using built-in methods?

In [33]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

Identity Matrix: Determinant is 0

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [48]:
np.random.rand(3,2)

array([[0.12421653, 0.77211553],
       [0.65352008, 0.07878486],
       [0.38045331, 0.21846412]])

In [55]:
np.random.randint(1, 10, (3,2))

array([[6, 6],
       [7, 1],
       [7, 6]])

<h2 style="color:rgb(246,99,09)"><b>Topic 3 : What are the attributes and methods of NumPy Array?

In [56]:
arr1 = np.arange(1,26)

In [57]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [58]:
arr1.shape

(25,)

In [62]:
arr5 = arr1.reshape(5,5)

In [63]:
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
arr5.reshape(3,4)

ValueError: cannot reshape array of size 25 into shape (3,4)

In [65]:
arr5.max()

25

In [66]:
arr5.min()

1

In [69]:
arr5.argmax()

24

In [70]:
arr5.argmin()

0

In [71]:
arr5.dtype

dtype('int32')

<h2 style="color:rgb(246,99,09)"><b>Topic 4 : How to perform indexing and selection of elements in 1-D NumPy Array?

In [73]:
arr6 = np.arange(1,10)

In [74]:
arr6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr6[3]

4

In [76]:
arr6[1:5]

array([2, 3, 4, 5])

In [77]:
arr6[1:5]=10

In [78]:
arr6

array([ 1, 10, 10, 10, 10,  6,  7,  8,  9])

In [79]:
arr6[:]=25

In [80]:
arr6

array([25, 25, 25, 25, 25, 25, 25, 25, 25])

In [81]:
arr7 = arr6.copy()

In [82]:
arr7

array([25, 25, 25, 25, 25, 25, 25, 25, 25])

In [83]:
arr7[:]=10

In [84]:
arr6

array([25, 25, 25, 25, 25, 25, 25, 25, 25])

In [85]:
arr7

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

<h2 style="color:rgb(246,99,09)"><b>Topic 5 : How to perform conditional selection using a boolean array?

In [86]:
arr8 = np.random.randint(0,100,30)

In [87]:
arr8

array([46, 65, 35, 38, 20, 81, 84,  6, 57, 91, 65, 24, 98, 64, 35, 22, 13,
       76, 65, 35, 26, 51, 79, 22, 54,  7, 99, 39, 76,  3])

In [88]:
bool_arr8 = arr8>50

In [89]:
bool_arr8

array([False,  True, False, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True, False, False, False,  True,
        True, False, False,  True,  True, False,  True, False,  True,
       False,  True, False])

In [90]:
arr8[bool_arr8]

array([65, 81, 84, 57, 91, 65, 98, 64, 76, 65, 51, 79, 54, 99, 76])

In [91]:
arr8[arr8<50]

array([46, 35, 38, 20,  6, 24, 35, 22, 13, 35, 26, 22,  7, 39,  3])

<h2 style="color:rgb(246,99,09)"><b>Topic 6 : How to perform operations with Arrays?    

<h2 style="color:blue"><b>Operations between Array and Array

In [92]:
a = np.arange(1,10,2)
b = np.arange(1,15,3)

In [93]:
a

array([1, 3, 5, 7, 9])

In [94]:
b

array([ 1,  4,  7, 10, 13])

In [95]:
a+b

array([ 2,  7, 12, 17, 22])

In [96]:
a-b

array([ 0, -1, -2, -3, -4])

In [97]:
a*b

array([  1,  12,  35,  70, 117])

<h2 style="color:blue"><b>Operations between Array and Scalar

In [98]:
a+3

array([ 4,  6,  8, 10, 12])

In [99]:
a-3

array([-2,  0,  2,  4,  6])

In [100]:
b*2

array([ 2,  8, 14, 20, 26])

In [101]:
b/2

array([0.5, 2. , 3.5, 5. , 6.5])

In [102]:
b//3

array([0, 1, 2, 3, 4], dtype=int32)

In [103]:
a**2

array([ 1,  9, 25, 49, 81], dtype=int32)

<h2 style="color:rgb(246,99,09)"><b>Topic 7 : How to perform with NumPy universal fuctions? 

In [104]:
a

array([1, 3, 5, 7, 9])

In [105]:
b

array([ 1,  4,  7, 10, 13])

In [106]:
np.add(b,a)


array([ 2,  7, 12, 17, 22])

In [107]:
np.subtract(b,a)

array([0, 1, 2, 3, 4])

In [108]:
np.multiply(b,a)

array([  1,  12,  35,  70, 117])

In [109]:
np.exp(b)

array([2.71828183e+00, 5.45981500e+01, 1.09663316e+03, 2.20264658e+04,
       4.42413392e+05])

In [110]:
np.sqrt(a)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ])

In [115]:
np.sin(b)

array([ 0.84147098, -0.7568025 ,  0.6569866 , -0.54402111,  0.42016704])

In [116]:
np.cos(a)

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026])

In [117]:
np.tan(b)

array([1.55740772, 1.15782128, 0.87144798, 0.64836083, 0.46302113])

In [118]:
np.log(b)

array([0.        , 1.38629436, 1.94591015, 2.30258509, 2.56494936])

In [121]:
b.cumsum(axis=0) #cumulative sum of all the elements

array([ 1,  5, 12, 22, 35], dtype=int32)

In [122]:
a.mean() # Average/mean of all values

5.0

In [128]:
np.median(a)

5.0

In [130]:
np.corrcoef(a) # Correlation coeff

1.0

In [133]:
c = np.array([4,9,2,7,10,1])

In [134]:
c

array([ 4,  9,  2,  7, 10,  1])

In [135]:
c.sort()

In [136]:
c

array([ 1,  2,  4,  7,  9, 10])

In [137]:
#Transposing array

In [138]:
a.T

array([1, 3, 5, 7, 9])

In [139]:
np.concatenate((a,b))

array([ 1,  3,  5,  7,  9,  1,  4,  7, 10, 13])

We will practice Numpy along side with the Machine Learning!